# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/.Xil/Vivado-7412-DESKTOP-U1OB0E7/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-2L
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/datapath/adder.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/datapath/alu.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/control_unit/auxdec.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/basys3_single_cycle_mips_validation/button_debouncer.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/basys3_single_cycle_mips_validation/clk_gen.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/control_unit/controlunit.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/datapath/datapath.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/memory/dmem.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/datapath/dreg.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/basys3_single_cycle_mips_validation/hex_to_7seg.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/memory/imem.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/basys3_single_cycle_mips_validation/led_mux.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/control_unit/maindec.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/mips/mips.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/mips/mips_top.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/datapath/mux2.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/datapath/regfile.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/datapath/signext.v}
      {C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/Assignment_5.srcs/sources_1/imports/basys3_single_cycle_mips_validation/mips_fpga.v}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top mips_fpga
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/Sidarth Shahri/Documents/CMPE 140 Assignments/Assignment 6/Vivado Files/.Xil/Vivado-7412-DESKTOP-U1OB0E7/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
